# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    # Deprecated
    - tenv
    # Other
    - depguard
    - err113
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gocritic
    - ireturn
    - perfsprint
